package fpt.fall2025.posetrainer.BroadcastReceiver;

import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.util.Log;

import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseUser;

import fpt.fall2025.posetrainer.Domain.Notification;
import fpt.fall2025.posetrainer.Helper.AppStateHelper;
import fpt.fall2025.posetrainer.Service.FirebaseService;
import fpt.fall2025.posetrainer.Service.NotificationHelper;

/**
 * BroadcastReceiver để nhận alarms từ AlarmManager
 */
public class WorkoutReminderReceiver extends BroadcastReceiver {
    private static final String TAG = "WorkoutReminderReceiver";

    @Override
    public void onReceive(Context context, Intent intent) {
        Log.d(TAG, "=== ĐÃ NHẬN BÁO THỨC NHẮC NHỞ TẬP LUYỆN ===");
        
        String workoutId = intent.getStringExtra("workoutId");
        int dayOfWeek = intent.getIntExtra("dayOfWeek", 0);
        int minutesBefore = intent.getIntExtra("minutesBefore", 0);
        
        Log.d(TAG, "WorkoutId: " + workoutId + ", dayOfWeek: " + dayOfWeek + ", minutesBefore: " + minutesBefore);
        
        // Kiểm tra xem có nên hiển thị notification không
        // Không hiển thị nếu app đang ở foreground và DailyFragment đang visible
        if (!AppStateHelper.shouldShowNotification(context)) {
            Log.d(TAG, "Thông báo bị ẩn: Người dùng đang xem DailyFragment (lịch tập)");
            // Vẫn lưu notification vào Firestore để tracking
            if (minutesBefore == 0) {
                saveNotificationToFirestore(workoutId, dayOfWeek);
            }
            return;
        }
        
        // Show notification to device
        Log.d(TAG, "Đang hiển thị thông báo trên thiết bị");
        NotificationHelper.showWorkoutReminderNotification(context, workoutId, dayOfWeek, minutesBefore);
        
        // Save notification to Firestore (only for the actual workout time, not reminders)
        if (minutesBefore == 0) {
            saveNotificationToFirestore(workoutId, dayOfWeek);
        }
        
        // Schedule next alarm for next week
        // Note: This should be handled by AlarmScheduler when schedule is loaded
    }

    /**
     * Save notification to Firestore when alarm triggers
     */
    private void saveNotificationToFirestore(String workoutId, int dayOfWeek) {
        FirebaseUser currentUser = FirebaseAuth.getInstance().getCurrentUser();
        if (currentUser == null) {
            Log.w(TAG, "Không có người dùng đăng nhập, không thể lưu thông báo");
            return;
        }

        String[] dayNames = {"", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy", "Chủ nhật"};
        String dayName = (dayOfWeek >= 1 && dayOfWeek <= 7) ? dayNames[dayOfWeek] : "Hôm nay";

        Notification notification = new Notification(
            null, // id - will be generated by Firestore
            currentUser.getUid(),
            "workout_reminder_sent", // type - indicates this was sent
            "Đến giờ tập luyện!",
            "Bạn có lịch tập vào " + dayName + ". Nhấn để bắt đầu tập luyện.",
            System.currentTimeMillis(), // sentAt - current time when notification is sent
            false // read
        );

        FirebaseService.getInstance().saveNotification(notification, success -> {
            if (success) {
                Log.d(TAG, "Đã lưu thông báo vào Firestore thành công");
            } else {
                Log.w(TAG, "Không thể lưu thông báo vào Firestore");
            }
        });
    }
}

